[package]
name = "art3mis"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
openzeppelin = "0.20.0"
starknet = "2.9.2"

[dev-dependencies]
openzeppelin_testing = "0.20.0"
snforge_std = "0.34.0"
# openzeppelin_testing = {path = "../cairo-contracts/packages/testing"}

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"